import { useEffect, useState } from 'react'
import { api } from '../api'
import { EmptyState, ErrorState, LoadingState } from '../components/State'
import type { BenchmarkRun } from '../types'

export default function BenchmarksPage() {
  const [runs, setRuns] = useState<BenchmarkRun[] | null>(null)
  const [error, setError] = useState<unknown>(null)
  useEffect(() => { api.benchmarks().then(setRuns).catch(setError) }, [])
  if (error) return <ErrorState error={error} />
  if (!runs) return <LoadingState />

  return (
    <div className="space-y-5">
      <div>
        <h1 className="text-2xl font-bold tracking-tight text-ink">Benchmarks</h1>
        <p className="mt-1 text-sm text-slate-500">Replay and network recovery measurements generated by the benchmark harness.</p>
      </div>
      {!runs.length && <EmptyState label="No benchmark runs stored in the backend yet. Run make benchmark to generate artifacts, then post them with scripts/publish_benchmark.py if desired." />}
      {runs.map(run => (
        <div key={run.id} className="card p-5">
          <div className="flex items-center justify-between">
            <div><h2 className="text-lg font-bold text-ink">{run.name}</h2><p className="text-sm text-slate-500">{new Date(run.created_at).toLocaleString()}</p></div>
          </div>
          <div className="mt-5 grid gap-3 md:grid-cols-4">
            {Object.entries(run.metrics).map(([key, value]) => (
              <div key={key} className="rounded-2xl bg-slate-50 p-4">
                <div className="text-xs font-semibold uppercase tracking-wide text-slate-500">{key.replaceAll('_', ' ')}</div>
                <div className="mt-2 text-xl font-bold text-ink">{String(value)}</div>
              </div>
            ))}
          </div>
        </div>
      ))}
      <div className="card p-5">
        <h2 className="text-lg font-bold text-ink">Local artifact workflow</h2>
        <pre className="mt-4 overflow-auto rounded-xl bg-slate-950 p-4 text-sm text-slate-100">make benchmark{"\n"}make assets</pre>
        <p className="mt-3 text-sm text-slate-500">The scripts write JSON, Markdown, and SVG charts to benchmarks/outputs and reports/generated.</p>
      </div>
    </div>
  )
}
